### ISSUE TITLE
当计算均值和方差的图片数量超过一定数量时，会出现报错：

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#11]
```
Traceback (most recent call last):
  File "easyai/tools/compute_images_mean.py", line 57, in <module>
    main()
  File "easyai/tools/compute_images_mean.py", line 51, in main
    mean, std = test.compute(options.inputPath)
  File "easyai/tools/compute_images_mean.py", line 39, in compute
    numpy_images = np.stack(numpy_images)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/numpy/core/shape_base.py", line 422, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError
```

**Comment by vitahlin** [comment]
一次性载入太多图片，内存不够
