### ISSUE TITLE
安霸工具转换出错

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#25]
在使用安霸工具时出现报错：
```
Traceback (most recent call last):
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnxparser.py", line 84, in <module>
    onnx_main()
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnxparser.py", line 75, in onnx_main
    from onnx_scanner import GraphBuilder
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnx_scanner.py", line 42, in <module>
    from caffe2.python.onnx import backend
  File "/usr/local/lib/python3.6/dist-packages/caffe2/python/onnx/backend.py", line 27, in <module>
    from caffe2.python import core, workspace, rnn_cell, gru_cell
  File "/usr/local/lib/python3.6/dist-packages/caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

**Comment by MiniBullLab** [comment]
```
pip3 install future
```

**Comment by MiniBullLab** [comment]
Could not find a version that satisfies the requirement onnxoptimizer>=0.1.1 (from onnx-simplifier->easy-converter==0.2) (from versions: 0.1.0)
No matching distribution found for onnxoptimizer>=0.1.1 (from onnx-simplifier->easy-converter==0.2)
@lpj0822

**Comment by MiniBullLab** [comment]
更新pip版本即可。
```
sudo pip3 install --upgrade pip
```
