### ISSUE TITLE
develop训练分割任务报错

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#30]
拉取最新的develop分支，运行训练脚本：
```
python3 easyai/train_task.py -t segment -i /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/train.txt -v /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/val.txt -m ./cfg/seg/mobilenetv2_fgseg.cfg -p /home/wfw/HASCO/all_wights/MobilenetV2_FgSegNetV2.pt -c ./log/config/segmention_config.json
```
出现以下报错：
```
import amp fail!
process start...
Using device: "cuda"
loss:convBNActivationBlock error
Traceback (most recent call last):
  File "easyai/train_task.py", line 52, in <module>
    main()
  File "easyai/train_task.py", line 47, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 27, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/home/wfw/EDGE/easy_ai/easyai/utility/registry.py", line 107, in build_from_cfg
    return obj_cls(**args)
  File "/home/wfw/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 22, in __init__
    self.model = self.torchModelProcess.create_model(self.model_args, gpu_id)
  File "/home/wfw/EDGE/easy_ai/easyai/torch_utility/torch_model_process.py", line 26, in create_model
    model = self.modelFactory.get_model(model_config)
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/model_factory.py", line 29, in get_model
    result = self.get_model_from_cfg(input_name, model_args)
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/model_factory.py", line 44, in get_model_from_cfg
    model = MyModel(model_define, path, default_args)
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/my_model.py", line 25, in __init__
    self.create_block_list()
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/my_model.py", line 30, in create_block_list
    backbone_block, self.backbone_name = self.creat_backbone()
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/my_model.py", line 60, in creat_backbone
    result = self.backbone_factory.get_backbone_model(self.default_args)
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/utility/backbone_factory.py", line 23, in get_backbone_model
    result = self.get_backbone_from_cfg(input_name)
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/utility/backbone_factory.py", line 36, in get_backbone_from_cfg
    model = MyBackbone(model_define)
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/utility/my_backbone.py", line 16, in __init__
    self.create_block_list()
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/utility/my_backbone.py", line 23, in create_block_list
    self.createTaskList.createOrderedDict(self.model_defines, base_out_channels)
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/create_model_list.py", line 75, in createOrderedDict
    self.create_loss(block_def)
  File "/home/wfw/EDGE/easy_ai/easyai/model/utility/create_model_list.py", line 221, in create_loss
    self.add_block_list(loss.get_name(), loss, self.filters)
AttributeError: 'NoneType' object has no attribute 'get_name'
```
@lpj0822

**Comment by lpj0822** [comment]
已经修改

**Comment by foww-0001** [comment]
拉取最新分支代码，训练出现错误。
```
/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/functional.py:2016: UserWarning: Using a target size (torch.Size([1, 436, 769])) that is different to the input size (torch.Size([1, 1, 436, 769])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "easyai/train_task.py", line 52, in <module>
    main()
  File "easyai/train_task.py", line 47, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 29, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 58, in train
    loss_value = self.compute_backward(images, segments, idx)
  File "/home/wfw/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 67, in compute_backward
    loss = self.compute_loss(output_list, targets)
  File "/home/wfw/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 86, in compute_loss
    loss = self.model.lossList[0](output, target)
  File "/home/wfw/EDGE/EdgeToolENV/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wfw/EDGE/easy_ai/easyai/loss/cls/ce2d_loss.py", line 114, in forward
    loss = self.compute_loss_from_weight(loss, target)
  File "/home/wfw/EDGE/easy_ai/easyai/loss/cls/ce2d_loss.py", line 88, in compute_loss_from_weight
    self.weight[1] * target.eq(1).type(loss.dtype) * loss
IndexError: index 1 is out of bounds for dimension 0 with size 1
```
@lpj0822

**Comment by lpj0822** [comment]
变量写错了，已经修改
