### ISSUE TITLE
训练分类报错

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#32]
拉取最新的develop分支代码，训练分类报错：
```
'int' object has no attribute 'backward'
Traceback (most recent call last):
  File "easyai/train_task.py", line 52, in <module>
    main()
  File "easyai/train_task.py", line 47, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 29, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/easy_ai/easyai/tasks/cls/classify_train.py", line 69, in train
    raise e
  File "/home/wfw/easy_ai/easyai/tasks/cls/classify_train.py", line 62, in train
    loss_value = self.compute_backward(images, targets, index)
  File "/home/wfw/easy_ai/easyai/tasks/cls/classify_train.py", line 78, in compute_backward
    self.loss_backward(loss)
  File "/home/wfw/easy_ai/easyai/tasks/utility/common_train.py", line 51, in loss_backward
    loss.backward()
AttributeError: 'int' object has no attribute 'backward'
```

**Comment by lpj0822** [comment]
交叉熵loss名称改为：crossEntropy2dLoss
