### ISSUE TITLE
classify inference报错

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#36]
运行classify inference：
```
python3 easyai/inference_task.py -t classify -i /home/wfw/data/VOCdevkit/caltech257_classify/ImageSets/val.txt -m classnet -w .easy_log/snapshot/cls_best.pt -c .easy_log/config/classify_config.json
```
出现报错：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 42, in <module>
    main()
  File "easyai/inference_task.py", line 37, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 27, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/cls/classify.py", line 29, in process
    prediction, _ = self.infer(image)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/cls/classify.py", line 53, in infer
    output_list = self.model(input_data.to(self.device))
AttributeError: 'NoneType' object has no attribute 'to'
```
@lpj0822

**Comment by foww-0001** [comment]
问题在于：
```
"normalize_type": -1,
```
./data_loader/utility/image_dataset_process.py中不存在normalize_type=-1的情况。
```
    def normalize(self, input_data, normalize_type, **param):
        result = None
        if normalize_type == 0:
            result = self.image_normalize(input_data)
        elif normalize_type == 1:
            mean = param['mean']
            std = param['std']
            normaliza_image = self.image_normalize(input_data)
            result = self.standard_normalize(normaliza_image, mean, std)
        elif normalize_type == 2:
            temp_x = self.image_normalize(input_data)
            result = (temp_x - 0.5) / 0.5
        return result
```
@lpj0822

**Comment by lpj0822** [comment]
已经更新
