### ISSUE TITLE
detect2d inference报错

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#37]
通过读入视频跑目标检测的结果，出现如下错误：
```
Traceback (most recent call last):
  File "easyai/inference_task.py", line 40, in <module>
    main()
  File "easyai/inference_task.py", line 35, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 26, in infer
    task.process(self.input_path, self.is_show)
  File "/home/wfw/EDGE/easy_ai/easyai/tasks/det2d/detect2d.py", line 32, in process
    for i, (file_path, src_image, img) in enumerate(dataloader):
  File "/home/wfw/EDGE/easy_ai/easyai/data_loader/utility/video_loader.py", line 43, in __next__
    pad_color=self.image_pad_color)
  File "/home/wfw/EDGE/easy_ai/easyai/data_loader/utility/image_dataset_process.py", line 23, in resize
    src_size = (src_image.shape[1], src_image.shape[0])  # [width, height]
AttributeError: 'tuple' object has no attribute 'shape'
```
定位到是读取视频时，返回两个值：
```
    def read_src_image(self, cv_image):
        src_image = None
        if self.data_channel == 1:
            src_image = self.dataset_process.cv_image_color_convert(cv_image, 0)
        elif self.data_channel == 3:
            src_image = self.dataset_process.cv_image_color_convert(cv_image, 1)
        else:
            print("read src image error!")
        return cv_image, src_image
```
但是调用的时候返回一个值：
```
        src_image = self.read_src_image(cv_image)
```
可修改为：
```
       _, src_image = self.read_src_image(cv_image)
```
@lpj0822

**Comment by lpj0822** [comment]
没有这行代码

**Comment by lpj0822** [comment]
问题已经修改
