### ISSUE TITLE
缺少NormalizationFunction

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#40]
拉取最新develop分支，运行缺少NormalizationFunction
```
Traceback (most recent call last):
  File "easyai/tools/model_tool/model_feature_show.py", line 9, in <module>
    from easyai.model.utility.model_factory import ModelFactory
  File "/home/wfw/EDGE/easy_ai/easyai/model/__init__.py", line 1, in <module>
    from . import backbone
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/__init__.py", line 1, in <module>
    from . import cls
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/cls/__init__.py", line 1, in <module>
    from . import resnet
  File "/home/wfw/EDGE/easy_ai/easyai/model/backbone/cls/resnet.py", line 9, in <module>
    from easyai.model.base_block.utility.utility_block import ConvBNActivationBlock
  File "/home/wfw/EDGE/easy_ai/easyai/model/base_block/utility/utility_block.py", line 9, in <module>
    from easyai.model.base_block.utility.normalization_layer import NormalizationFunction
  File "/home/wfw/EDGE/easy_ai/easyai/model/base_block/utility/normalization_layer.py", line 9, in <module>
    from easyai.model.base_block.utility.utility_layer import EmptyLayer
  File "/home/wfw/EDGE/easy_ai/easyai/model/base_block/utility/utility_layer.py", line 8, in <module>
    from easyai.model.base_block.utility.normalization_layer import NormalizationFunction
ImportError: cannot import name 'NormalizationFunction'
```
@lpj0822

**Comment by lpj0822** [comment]
已经修改
