### ISSUE TITLE
ClassNet运行报错

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#42]
运行ClassNET_tool.sh出现报错：
```
process start...
./log/config/classify_config.json not exits
Using device: "cuda"
./log/config/classify_config.json not exits
./log/config/classify_config.json not exits
Using device: "cuda"
Loading pretainModel from
/usr/local/lib/python3.6/dist-packages/easy_tools/./data/classnet.pt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/easy_tools/easy_ai.py", line
67, in <module>
    train_main()
  File "/usr/local/lib/python3.6/dist-packages/easy_tools/easy_ai.py", line
56, in train_main
    train_process.classify_model_train(dir_name)
  File "easy_tools/easyai_train.py", line 33, in
easy_tools.easyai_train.EasyAiModelTrain.classify_model_train
  File "easyai/train_task.py", line 29, in easyai.train_task.TrainTask.train
  File "easyai/tasks/cls/classify_train.py", line 53, in
easyai.tasks.cls.classify_train.ClassifyTrain.train
  File "easyai/data_loader/cls/classify_dataloader.py", line 52, in
easyai.data_loader.cls.classify_dataloader.get_classify_train_dataloader
  File "easyai/data_loader/cls/classify_dataloader.py", line 21, in
easyai.data_loader.cls.classify_dataloader.ClassifyDataloader.__init__
  File "easyai/data_loader/cls/classify_sample.py", line 19, in
easyai.data_loader.cls.classify_sample.ClassifySample.read_sample
  File "easyai/data_loader/cls/classify_sample.py", line 46, in
easyai.data_loader.cls.classify_sample.ClassifySample.get_image_and_label_li
st
TypeError: must be real number, not str
Failed to start easy_ai
```
@lpj0822

**Comment by lpj0822** [comment]
问题无法复现

**Comment by lpj0822** [comment]
自动生成trian.txt与val.txt需要，当前数据集没有这两个文件，如果有则不会自动生成

**Comment by foww-0001** [comment]
FAQ中加入该问题，解决方案为删除ImageSets文件夹，如需使用自己定义的训练和测试数据，请参照正确的格式写。
@lpj0822
