### ISSUE TITLE
训练segnet报错

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#44]
运行segnet的命令行，出现报错：
```
python3 easyai/train_task.py -t segment -i /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/train.txt -v /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/val.txt -m ./cfg/seg/mobilenetv2_fgseg.cfg -p /home/wfw/workspace/HASCO/all_wights/MobilenetV2_FgSegNetV2.pt
```
报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 52, in <module>
    main()
  File "easyai/train_task.py", line 47, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 29, in train
    task.train(self.train_path, self.val_path)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 62, in train
    self.test(val_path, epoch, save_model_path)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/seg/segment_train.py", line 125, in test
    score, class_score, average_loss = self.segment_test.test(val_path)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/seg/segment_test.py", line 43, in test
    result, _ = self.segment_inference.postprocess(prediction, self.threshold)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/seg/segment.py", line 73, in postprocess
    result)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/seg/segment_result_process.py", line 29, in resize_segmention_result
    image_size)
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/data_loader/utility/image_dataset_process.py", line 94, in get_square_size
    ratio = min(float(dst_size[0]) / src_size[0], float(dst_size[1]) / src_size[1])
ZeroDivisionError: float division by zero
```
@lpj0822 #

**Comment by lpj0822** [comment]
没有设置src_size值

**Comment by foww-0001** [comment]
训练原始的cfg文件精度提升不上去。具体的运行脚本是：
```
python3 easyai/train_task.py -t segment -i /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/train.txt -v /home/wfw/data/VOCdevkit/CarScratch_segment/ImageSets/val.txt -m ./cfg/seg/mobilenetv2_fgseg.cfg -p /home/wfw/workspace/HASCO/all_wights/MobilenetV2_FgSegNetV2.pt
```
分割的精度如下：
```
Overall Acc: 	 0.9987664950112649
Mean Acc : 	 0.5011425594653542
FreqW Acc : 	 0.9975429305589304
Mean IoU : 	 0.5005221979327251
Val epoch loss: 0.0476088
```
