### ISSUE TITLE
classnet,denet,segnet网络输入输出层名固定

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_ai#45]
- [x] 1.classnet,denet,segnet onnx网络输出层名固定
- [x] 2.修改下位机代码，与下位机联调(另建Issue处理)

**Comment by lpj0822** [comment]
层名已经固定，代码修改完成
| task | 输入层名称 | 输出层名称 |
| :------: | :------: | :------: | 
| classnet | cls_input | cls_output |
| DeNet | det_input | det_output0,det_output1,det_output2 |
| segnet | seg_input | seg_output |

**Comment by foww-0001** [comment]
## classnet 
classnet在easy_tools下进行训练，得到的onnx网络通过网页显示，发现输入层名称为cls_input，输出层名称为cls_output。

转换结果可以得到classnet.bin文件，但是后面的inference还需要进一步测试。
注意的是，在转换过程中打印一些warning：
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "C.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```
@lpj0822

**Comment by foww-0001** [comment]
##segnet

segnet在easy_tools下进行训练，得到的onnx网络通过网页显示，发现输入层名称为seg_input，输出层名称为seg_output。

转换结果可以得到segnet.bin文件，但是后面的inference还需要进一步测试。

**Comment by foww-0001** [comment]
转换的shell脚本需要修改，1. log的路径需要修改 2. outputLayerName="o: 后面的输出层名称需要修改。

**Comment by foww-0001** [comment]
## denet
---
segnet在easy_tools下进行训练，得到的prototxt的输入层名称为data，输出层分别为det_output0，det_output1，det_output2。
denet转换出错，错误如下：
```
Traceback (most recent call last):
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/caffeparser.py", line 29, in <module>
    import io_nodes
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/io_nodes.py", line 26, in <module>
    import caffe_common as cfc
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/caffe/caffe_common.py", line 23, in <module>
    from caffe import Net
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/opt/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libglog.so.0.3.5: cannot open shared object file: No such file or directory
```
@lpj0822
