### ISSUE TITLE
classnet，detnet，segnet的模块参数修改

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#5]
1. 分割网络修改网络输入尺寸
2. 分类网络切换backbone
3. segnet换成代码形式
4. 检测网络修改anchors
5. 数据增强方法修改（对现有方法进行排列组合）
6. 数据增强修改resize_type参数

**Comment by foww-0001** [comment]
classnet中，换backbone: 由resnet18换成mobilenetv2_120d网络，在caltech257_classify数据集中，精度64.1提升到83.2。

**Comment by foww-0001** [comment]
### 换anchors

anchors的大小目前在object365上重新做了聚类，

**Comment by foww-0001** [comment]
### 数据增强方法修改（对现有方法进行排列组合）

目前easyai中有的数据增强方式：

- 图像扰动，
- 改变亮度、对比对、饱和度、色调
加噪声
随机缩放
随机裁剪（random crop）
翻转旋转
随机擦除（random erase）
Cutout
MixUp
CutMix

**Comment by MiniBullLab** [comment]
拉取最新分支代码，运行分类训练脚本：
```
python3 easyai/train_task.py -t classify -i /home/wfw/easy_data/ImageSets/train.txt -v /home/wfw/easy_data/ImageSets/val.txt -m classnet
```
出现下面报错：
```
import amp fail!
Traceback (most recent call last):
  File "easyai/train_task.py", line 5, in <module>
    from easyai.tasks.utility.registry import REGISTERED_TRAIN_TASK
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/__init__.py", line 2, in <module>
    from . import det2d
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/det2d/__init__.py", line 3, in <module>
    from . import detect2d_train
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/det2d/detect2d_train.py", line 6, in <module>
    from easyai.data_loader.det2d.det2d_train_dataloader import get_detect2d_train_dataloader
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/data_loader/det2d/det2d_train_dataloader.py", line 15, in <module>
    from easyai.tools.sample_tool.create_detection_sample import CreateDetectionSample
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tools/sample_tool/create_detection_sample.py", line 13, in <module>
    from easyai.tools.sample_tool.sample_info_get import DetectionSampleProcess
ImportError: cannot import name 'DetectionSampleProcess'
```

**Comment by MiniBullLab** [comment]
已经更新
