### ISSUE TITLE
通过easy_tools测试所有功能模块

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#50]
1.测试OK_NG是否运行正常
2.测试分类是否运行正常
3.测试检测是否运行正常
4.测试分割是否运行正常
5.测试界面训练功能
6.测试界面test功能

**Comment by MiniBullLab** [comment]
## 2.测试分类是否运行正常
发现分类中classify_dataloader.py中get_classify_val_dataloader的batch_size = data_config.train_batch_size写错了，应改为test_batch_size。
@lpj0822

**Comment by foww-0001** [comment]
## 2.测试分类是否运行正常
猫狗分类精度降低，由原来的93.5%掉到了90%。

**Comment by foww-0001** [comment]
```
    if options.task_name.strip() == "NG_OK":
        train_process.binary_classidy_model_train(dir_name)
    if options.task_name.strip() == "ClassNet":
        train_process.classify_model_train(dir_name)
    elif options.task_name.strip() == "DeNET":
        train_process.det2d_model_train(dir_name)
    elif options.task_name.strip() == "SegNET":
        train_process.segment_model_train(dir_name)
```
可以统一NET的写法为Net

**Comment by foww-0001** [comment]
## 4.测试分割是否运行正常
```
process start...
../../data/seg/ImageSets/train.txt exits
./.easy_log/config/segmention_config.json not exits
Using device: "cuda"
Traceback (most recent call last):
  File "easy_tools/easy_ai.py", line 69, in <module>
    train_main()
  File "easy_tools/easy_ai.py", line 62, in train_main
    train_process.segment_model_train(dir_name)
  File "/easy_data/code/easy_ai/easy_tools/easyai_train.py", line 80, in segment_model_train
    train_task.train(cfg_path, self.gpu_id, self.config_path, pretrain_model_path)
  File "/easy_data/code/easy_ai/easyai/train_task.py", line 29, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/easy_data/code/easy_ai/easyai/utility/registry.py", line 107, in build_from_cfg
    return obj_cls(**args)
  File "/easy_data/code/easy_ai/easyai/tasks/seg/segment_train.py", line 22, in __init__
    self.model = self.torchModelProcess.create_model(self.model_args, gpu_id)
  File "/easy_data/code/easy_ai/easyai/torch_utility/torch_model_process.py", line 26, in create_model
    model = self.modelFactory.get_model(model_config)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_factory.py", line 29, in get_model
    result = self.get_model_from_cfg(input_name, model_args)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_factory.py", line 43, in get_model_from_cfg
    model_define = self.modelParse.readCfgFile(cfg_path)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_parse.py", line 13, in readCfgFile
    file = open(cfgPath, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'easy_tools/./data/segnet.cfg'
```

**Comment by MiniBullLab** [comment]
segnet 输入512*448

**Comment by lpj0822** [comment]
代码以及修改

**Comment by foww-0001** [comment]
## 5.测试所有tools功能运行正常
---
测试model_block_print.py -o onnx网络，报错：
```
input param error
```

**Comment by foww-0001** [comment]
测试model_net_show.py -b vgg11，关于netron的报错：
```
Traceback (most recent call last):
  File "easyai/tools/model_tool/model_net_show.py", line 46, in <module>
    show.model_show(options.model)
  File "easyai/tools/model_tool/model_net_show.py", line 23, in model_show
    self.show_process.show_from_model(model)
  File "/easy_data/code/easy_ai/easyai/torch_utility/torch_onnx/model_show.py", line 25, in show_from_model
    self.show_from_onnx(save_onnx_path)
  File "/easy_data/code/easy_ai/easyai/torch_utility/torch_onnx/model_show.py", line 16, in show_from_onnx
    netron.start(onnx_path, port=9999, host='localhost')
TypeError: start() got an unexpected keyword argument 'port'
```
和原始的代码比对过，版本号不同，原始的版本号为4.6.9，而最新的版本号为4.8.0。
经过试验发现4.8.0没有port参数输入。

**Comment by foww-0001** [comment]
测试model_summary，考虑需要把输入也作为参数进行输入，因为不同输入大小对于算力影响也很大。

**Comment by foww-0001** [comment]
测试model_to_onnx.py -t classify -b resnet18，测试backbone输入时，报错：
```
Traceback (most recent call last):
  File "easyai/tools/model_tool/model_to_onnx.py", line 62, in <module>
    main(options)
  File "easyai/tools/model_tool/model_to_onnx.py", line 54, in main
    elif input_param.base_model is not None:
AttributeError: 'Values' object has no attribute 'base_model'
```

**Comment by foww-0001** [comment]
测试show_lr_scheduler.py时，出现报错：
```
Traceback (most recent call last):
  File "easyai/tools/model_tool/show_lr_scheduler.py", line 7, in <module>
    from easyai.solver.optimizer.torch_optimizer import TorchOptimizer
ImportError: cannot import name 'TorchOptimizer'
```

**Comment by foww-0001** [comment]
测试compute_images_mean，发现低于5000张的会很快计算出来，超过一万张的会长时间不出结果， 还会报错，并且导致机器内存耗光。

**Comment by foww-0001** [comment]
测试create_detection_anchors.py，虽然图片正常可以读到，但是会报错，需要进一步测试问题所在：
```
Traceback (most recent call last):
  File "easyai/tools/parameter/create_detection_anchors.py", line 141, in <module>
    test()
  File "easyai/tools/parameter/create_detection_anchors.py", line 136, in test
    test.get_anchors(9)
  File "easyai/tools/parameter/create_detection_anchors.py", line 37, in get_anchors
    indices = [random.randrange(wh_numpy.shape[0]) for _ in range(number)]
  File "easyai/tools/parameter/create_detection_anchors.py", line 37, in <listcomp>
    indices = [random.randrange(wh_numpy.shape[0]) for _ in range(number)]
  File "/usr/lib/python3.6/random.py", line 189, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()
```

**Comment by lpj0822** [comment]
以上bug已经修改并提交

**Comment by vitahlin** [comment]
测试模型load有问题
