### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#52]
拉取最新代码分支报错：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 5, in <module>
    from easyai.tasks.utility.registry import REGISTERED_TRAIN_TASK
  File "/easy_data/code/easy_ai/easyai/tasks/__init__.py", line 1, in <module>
    from . import cls
  File "/easy_data/code/easy_ai/easyai/tasks/cls/__init__.py", line 1, in <module>
    from . import classify
  File "/easy_data/code/easy_ai/easyai/tasks/cls/classify.py", line 7, in <module>
    from easyai.tasks.utility.base_inference import BaseInference
  File "/easy_data/code/easy_ai/easyai/tasks/utility/base_inference.py", line 12, in <module>
    from easyai.torch_utility.torch_model_process import TorchModelProcess
  File "/easy_data/code/easy_ai/easyai/torch_utility/torch_model_process.py", line 10, in <module>
    from easyai.model.utility.model_factory import ModelFactory
  File "/easy_data/code/easy_ai/easyai/model/__init__.py", line 1, in <module>
    from . import model_block
  File "/easy_data/code/easy_ai/easyai/model/model_block/__init__.py", line 1, in <module>
    from . import backbone
  File "/easy_data/code/easy_ai/easyai/model/model_block/backbone/__init__.py", line 1, in <module>
    from . import cls
  File "/easy_data/code/easy_ai/easyai/model/model_block/backbone/cls/__init__.py", line 21, in <module>
    from . import shufflenetv2
  File "/easy_data/code/easy_ai/easyai/model/model_block/backbone/cls/shufflenetv2.py", line 10, in <module>
    from easyai.model.model_block.base_block.utility.pooling_layer import MyMaxPool2d
  File "/easy_data/code/easy_ai/easyai/model/model_block/base_block/utility/pooling_layer.py", line 7, in <module>
    from easyai.base_algorithm.roi_align import ROIAlign
  File "/easy_data/code/easy_ai/easyai/base_algorithm/roi_align.py", line 8, in <module>
    from maskrcnn_benchmark import _C
ModuleNotFoundError: No module named 'maskrcnn_benchmark'
```
@lpj0822

**Comment by lpj0822** [comment]
问题已经修改，再试一下
@foww-0001
