### ISSUE TITLE
AttributeError: type object 'TaskName' has no attribute 'KeyPoints2d_Task'

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#53]
拉取最新代码，测试发生报错：
```
Traceback (most recent call last):
  File "easy_tools/easy_ai.py", line 8, in <module>
    from easy_tools.easyai_train import EasyAiModelTrain
  File "/easy_data/code/easy_ai/easy_tools/easyai_train.py", line 7, in <module>
    from easyai.train_task import TrainTask
  File "/easy_data/code/easy_ai/easyai/train_task.py", line 5, in <module>
    from easyai.tasks.utility.registry import REGISTERED_TRAIN_TASK
  File "/easy_data/code/easy_ai/easyai/tasks/__init__.py", line 4, in <module>
    from . import keypoint2d
  File "/easy_data/code/easy_ai/easyai/tasks/keypoint2d/__init__.py", line 1, in <module>
    from . import key_points2d
  File "/easy_data/code/easy_ai/easyai/tasks/keypoint2d/key_points2d.py", line 13, in <module>
    @REGISTERED_INFERENCE_TASK.register_module(TaskName.KeyPoints2d_Task)
AttributeError: type object 'TaskName' has no attribute 'KeyPoints2d_Task'
```
@lpj0822

**Comment by lpj0822** [comment]
已经修改，拉取最新代码
