### ISSUE TITLE
NameError: name 'amp' is not defined

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#56]
```
import _C fail!
import amp fail!
Traceback (most recent call last):
  File "easyai/train_task.py", line 5, in <module>
    from easyai.tasks.utility.registry import REGISTERED_TRAIN_TASK
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/__init__.py", line 1, in <module>
    from . import cls
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/cls/__init__.py", line 1, in <module>
    from . import classify
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/cls/classify.py", line 7, in <module>
    from easyai.tasks.utility.base_inference import BaseInference
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/tasks/utility/base_inference.py", line 12, in <module>
    from easyai.torch_utility.torch_model_process import TorchModelProcess
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/torch_utility/torch_model_process.py", line 10, in <module>
    from easyai.model.utility.model_factory import ModelFactory
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/__init__.py", line 1, in <module>
    from . import model_block
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/model_block/__init__.py", line 1, in <module>
    from . import backbone
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/model_block/backbone/__init__.py", line 1, in <module>
    from . import cls
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/model_block/backbone/cls/__init__.py", line 21, in <module>
    from . import shufflenetv2
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/model_block/backbone/cls/shufflenetv2.py", line 10, in <module>
    from easyai.model.model_block.base_block.utility.pooling_layer import MyMaxPool2d
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/model/model_block/base_block/utility/pooling_layer.py", line 7, in <module>
    from easyai.base_algorithm.roi_align import ROIAlign
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/base_algorithm/roi_align.py", line 58, in <module>
    class ROIAlign(nn.Module):
  File "/home/wfw/workspace/EDGE/easy_ai/easyai/base_algorithm/roi_align.py", line 65, in ROIAlign
    @amp.float_function
NameError: name 'amp' is not defined
```

**Comment by lpj0822** [comment]
bug已经修改

**Comment by lpj0822** [comment]
bug已经修改
