### ISSUE TITLE
NameError: name 'nn' is not defined

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#58]
拉取最新代码，运行segnet训练：
```
python3 easyai/train_task.py -t segment -i ../../data/seg/ImageSets/train.txt -v ../../data/seg/ImageSets/val.txt -m segnet -p ./easy_tools/data/segnet.pt -c .easy_log/config/segmention_config.json
```
出现以下报错：
```
import _C fail!
import _C or amp fail!
process start...
Using device: "cuda"
Traceback (most recent call last):
  File "easyai/train_task.py", line 61, in <module>
    main()
  File "easyai/train_task.py", line 56, in main
    train_task.train(options.model, 0, options.config_path, options.pretrainModel)
  File "easyai/train_task.py", line 29, in train
    task = build_from_cfg(task_args, REGISTERED_TRAIN_TASK)
  File "/easy_data/code/easy_ai/easyai/utility/registry.py", line 107, in build_from_cfg
    return obj_cls(**args)
  File "/easy_data/code/easy_ai/easyai/tasks/seg/segment_train.py", line 22, in __init__
    self.model = self.torchModelProcess.create_model(self.model_args, gpu_id)
  File "/easy_data/code/easy_ai/easyai/torch_utility/torch_model_process.py", line 26, in create_model
    model = self.modelFactory.get_model(model_config)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_factory.py", line 33, in get_model
    result = self.get_model_from_name(model_args)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_factory.py", line 60, in get_model_from_name
    model = self.get_seg_model(model_config)
  File "/easy_data/code/easy_ai/easyai/model/utility/model_factory.py", line 82, in get_seg_model
    model = build_from_cfg(model_config, REGISTERED_SEG_MODEL)
  File "/easy_data/code/easy_ai/easyai/utility/registry.py", line 107, in build_from_cfg
    return obj_cls(**args)
  File "/easy_data/code/easy_ai/easyai/model/seg/segnet.py", line 15, in __init__
    super().__init__(data_channel, 1)
  File "/easy_data/code/easy_ai/easyai/model/seg/fgsegnet.py", line 28, in __init__
    self.create_block_list()
  File "/easy_data/code/easy_ai/easyai/model/seg/fgsegnet.py", line 53, in create_block_list
    conv2 = nn.Conv2d(64, 64, kernel_size=1, stride=1, padding=0)
NameError: name 'nn' is not defined
```

**Comment by lpj0822** [comment]
bug已经修改
