### ISSUE TITLE
AttributeError: 'ResnetPose' object has no attribute 'pose_model'

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#59]
跑pose2d中的ResnetPose报错：
```
import _C fail!
import _C or amp fail!
process start...
./.easy_log/config/pose2d_config.json not exits
Using device: "cuda"
Loading model weights/latest.pt fail
1/7 Traceback (most recent call last):
  File "easyai/inference_task.py", line 42, in <module>
    main()
  File "easyai/inference_task.py", line 37, in main
    inference_task.infer(options.model, 0, options.weights, options.config_path)
  File "easyai/inference_task.py", line 27, in infer
    task.process(self.input_path, self.data_type, self.is_show)
  File "/easy_data/code/easy_ai/easyai/tasks/pose2d/pose2d.py", line 33, in process
    objects_pose = self.single_image_process(self.src_size, img)
  File "/easy_data/code/easy_ai/easyai/tasks/pose2d/pose2d.py", line 41, in single_image_process
    prediction, _ = self.infer(input_image)
  File "/easy_data/code/easy_ai/easyai/tasks/pose2d/pose2d.py", line 50, in infer
    output = self.compute_output(output_list)
  File "/easy_data/code/easy_ai/easyai/tasks/pose2d/pose2d.py", line 55, in compute_output
    loss_count = len(self.model.pose_model.lossList)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResnetPose' object has no attribute 'pose_model'
```

**Comment by lpj0822** [comment]
已经修改
