### ISSUE TITLE
ImportError: cannot import name 'CalculateMeanAp'

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_ai#64]
拉取最新代码测试easy_tools报错：
```
Traceback (most recent call last):
  File "easy_tools/easy_ai.py", line 8, in <module>
    from easy_tools.easyai_train import EasyAiModelTrain
  File "/easy_data/code/easy_ai/easy_tools/easyai_train.py", line 6, in <module>
    from easyai.tools.utility.copy_image import CopyImage
  File "/easy_data/code/easy_ai/easyai/tools/__init__.py", line 1, in <module>
    from . import offline_test
  File "/easy_data/code/easy_ai/easyai/tools/offline_test/__init__.py", line 2, in <module>
    from . import offline_det2d_evaluation
  File "/easy_data/code/easy_ai/easyai/tools/offline_test/offline_det2d_evaluation.py", line 5, in <module>
    from easyai.evaluation.calculate_rect_AP import CalculateMeanAp
ImportError: cannot import name 'CalculateMeanAp'
```

**Comment by lpj0822** [comment]
已经修改该bug
