### ISSUE TITLE
TypeError: module must be a class, but got <class 'function'>

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#68]
拉取最新代码，训练分割模型：
```
python3 easyai/train_task.py -t segment -i ../../data/seg/ImageSets/train.txt -v ../../data/seg/ImageSets/val.txt -m segnet -p ./easy_tools/data/segnet.pt -c .easy_log/config/segmention_config.json 
```
报错如下：
```
Traceback (most recent call last):
  File "easyai/train_task.py", line 5, in <module>
    from easyai.tasks.utility.registry import REGISTERED_TRAIN_TASK
  File "/easy_data/code/easy_ai/easyai/tasks/__init__.py", line 1, in <module>
    from . import cls
  File "/easy_data/code/easy_ai/easyai/tasks/cls/__init__.py", line 2, in <module>
    from . import classify_test
  File "/easy_data/code/easy_ai/easyai/tasks/cls/classify_test.py", line 7, in <module>
    from easyai.data_loader.cls.classify_dataloader import get_classify_val_dataloader
  File "/easy_data/code/easy_ai/easyai/data_loader/cls/classify_dataloader.py", line 44, in <module>
    def get_classify_train_dataloader(train_path, data_config, num_workers=8):
  File "/easy_data/code/easy_ai/easyai/utility/registry.py", line 73, in deco
    self._register_module(cls, cls_name)
  File "/easy_data/code/easy_ai/easyai/utility/registry.py", line 60, in _register_module
    "module must be a class, but got {}".format(type(module_class))
TypeError: module must be a class, but got <class 'function'>
```

**Comment by lpj0822** [comment]
bug已经修改
