### ISSUE TITLE
onnx调用报错IndexError: _Map_base::at

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_ai#72]
edge_tools分支转换分类网络出错：
```
Traceback (most recent call last):
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnxparser.py", line 84, in <module>
    onnx_main()
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnxparser.py", line 77, in onnx_main
    onnxToAmbaCnn = GraphBuilder(params, prim_composer, json_retcode, onnx_factory)
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnx_scanner.py", line 93, in __init__
    self.__init_builder()
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnx_scanner.py", line 182, in __init_builder
    self.__init_shapes()
  File "/usr/local/amba-cv-tools-2.1.7-20190815.ubuntu-18.04/cv2/tv2/release/AmbaCnnUtils/cv2.1.7.408/parser/onnx/onnx_scanner.py", line 161, in __init_shapes
    self.caffe2Rep = backend.prepare(self.OnnxModel, device='CPU')
  File "/usr/local/lib/python3.6/dist-packages/caffe2/python/onnx/backend.py", line 708, in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
  File "/usr/local/lib/python3.6/dist-packages/caffe2/python/onnx/backend.py", line 875, in _onnx_model_to_caffe2_net
    onnx_model = onnx.utils.polish_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/utils.py", line 21, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at
```

**Comment by foww-0001** [comment]
发现requirmnets.txt中没有定义torch的版本号。

**Comment by vitahlin** [comment]
目前`torch`先在requirmnets.txt中定义，后续尽量迁移到docker配置中。
